# Generated by Django 5.2.6 on 2025-10-22 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=155)),
                ('upsw', models.CharField(max_length=155)),
                ('type', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_new_subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clg_teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, unique=True)),
                ('contact', models.CharField(max_length=13, unique=True)),
                ('stafflogin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.logindata')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.subject')),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contact', models.CharField(max_length=13)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('post', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('loginstd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.logindata')),
                ('std_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Set_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_days', models.CharField(choices=[('Monday', 'MON'), ('Tuesday', 'TUE'), ('Wednesday', 'WED'), ('Thursday', 'THURS'), ('FRIDAY', 'FRI')], max_length=15)),
                ('period', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th')], max_length=5)),
                ('staffs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.clg_teachers')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.subject')),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addnote', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.subject')),
            ],
        ),
    ]
