# Generated by Django 5.2.6 on 2025-10-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clg_teachers',
            name='sub',
        ),
        migrations.AddField(
            model_name='clg_teachers',
            name='sub',
            field=models.ManyToManyField(to='Teachers.subject'),
        ),
    ]
