# Generated by Django 5.2.6 on 2025-10-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_remove_clg_teachers_sub_clg_teachers_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='addnote',
            field=models.TextField(),
        ),
    ]
