# Generated by Django 5.2.6 on 2025-10-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0003_alter_notes_addnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='addnote',
            field=models.CharField(max_length=2000),
        ),
    ]
