# Generated by Django 5.2.6 on 2025-10-27 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0004_alter_notes_addnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.students')),
                ('subj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.subject')),
            ],
        ),
    ]
