# Generated by Django 5.2.6 on 2025-10-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0006_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subj', 'date')},
        ),
    ]
